apiVersion: v1
kind: Service
metadata:
  name: kube-sample
  labels:
    app: kube-sample
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: kube-sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-sample
  labels:
    app: kube-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-sample
  template:
    metadata:
      labels:
        app: kube-sample
    spec:
      containers:
      - name: kube-sample
        image: evgdim/kubernetes-sample:0.0.1
        ports:
        - containerPort: 8080